from distutils.core import setup
setup(
    name='LSJuicer',
    version='0.1dev',
    author='Ardo Illaste',
    author_email='ardo.illaste@gmail.com',
    packages=['lsjuicer',
            'lsjuicer.data',
            'lsjuicer.data.analysis',
            'lsjuicer.data.models',
            'lsjuicer.data.pipes',
            'lsjuicer.inout',
            'lsjuicer.inout.converters',
            'lsjuicer.inout.readers',
            'lsjuicer.inout.db',
            'lsjuicer.resources',
            'lsjuicer.static',
            'lsjuicer.ui.items',
            'lsjuicer.ui.scenes',
            'lsjuicer.ui.plot',
            'lsjuicer.ui.tabs',
            'lsjuicer.ui.views',
            'lsjuicer.ui.widgets',
            'lsjuicer.ui.windows',
            'lsjuicer.util',
              ],
    scripts=['bin/run_qt.py'],
    url='https://code.google.com/p/lsjuicer/',
    license='LICENSE.txt',
    description='',
    long_description=open('README.txt').read(),
    #install_requires=[
    #    "SQLAlchemy>=0.8.1",
    #    "alembic>=0.5.0",
    #    "numpy>=1.7.1",
    #    "scikit-learn>=0.13.1",
    #    "scikits-image>=0.7.1",
    #    "scipy>=0.12.0",
    #    "webcolors>=1.4",
    #],
)
